services:
  - type: web
    name: booktracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: booktracker-db
          property: connectionString

databases:
  - name: booktracker-db
    databaseName: booktracker
    user: booktracker